# This file was generated by GoReleaser. DO NOT EDIT.
cask "fin" do
  name "fin"
  desc "MCP server for git and Quip operations"
  homepage "https://github.com/anhpngt/fin-releases"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fin"

  on_macos do
    on_arm do
      url "https://github.com/anhpngt/fin-releases/releases/download/v#{version}/fin_v#{version}_darwin_arm64.tar.gz"
      sha256 "38de4e9cb761d21069d23034fd65d4fa102f50b611b2bc7e1fe0f2691491a732"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anhpngt/fin-releases/releases/download/v#{version}/fin_v#{version}_linux_amd64.tar.gz"
      sha256 "387bea93c7503beb35f8bddfe3dee35639ce337189ef9c411983174660cddab1"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fin"]
  end

  caveats do
    "To use fin as an MCP server in Claude Code, run:"
    "  claude mcp add -s user fin -- fin"
    ""
    "To enable Quip tools, set FIN_QUIP_TOKEN in your shell profile:"
    "  export FIN_QUIP_TOKEN=your-quip-token-here"
    ""
    "To verify it was added:"
    "  claude mcp list"
  end

  # No zap stanza required
end
