# This file was generated by GoReleaser. DO NOT EDIT.
cask "fin" do
  name "fin"
  desc "MCP server for git operations"
  homepage "https://github.com/anhpngt/fin-releases"
  version "0.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fin"

  on_macos do
    on_arm do
      url "https://github.com/anhpngt/fin-releases/releases/download/v#{version}/fin_v#{version}_darwin_arm64.tar.gz"
      sha256 "8ced6099a39b7972f97364b9452157265fdaee7edb9fc49a96aea9d25d780589"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/anhpngt/fin-releases/releases/download/v#{version}/fin_v#{version}_linux_amd64.tar.gz"
      sha256 "bba8813114ac3a965308df17c6840b52112dc27b0f34a86bfdd53a59c2886ec9"
    end
  end

  caveats do
    "To use fin as an MCP server in Claude Code, run:"
    "  claude mcp add fin fin"
    ""
    "To verify it was added:"
    "  claude mcp list"
  end

  # No zap stanza required
end
