# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcpt < Formula
  desc "MCP server for git operations"
  homepage "https://github.com/anhpngt/mcpt-releases"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anhpngt/mcpt-releases/releases/download/v0.0.6/mcpt_v0.0.6_darwin_amd64.tar.gz"
      sha256 "a1464a0d8f6c22f91ae754c74fbf5155e556763f8beb55d0ad672272a5080904"

      def install
        bin.install "mcpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anhpngt/mcpt-releases/releases/download/v0.0.6/mcpt_v0.0.6_darwin_arm64.tar.gz"
      sha256 "8352d97af855f83cddc3afbc807207c8aaa89cb502c6415bc6c60a615677cc19"

      def install
        bin.install "mcpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anhpngt/mcpt-releases/releases/download/v0.0.6/mcpt_v0.0.6_linux_amd64.tar.gz"
      sha256 "cda19ce738bdcc71b1cb2cdbe993045d59bd9034dcfdfedd4b045866dc390d65"
      def install
        bin.install "mcpt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anhpngt/mcpt-releases/releases/download/v0.0.6/mcpt_v0.0.6_linux_arm64.tar.gz"
      sha256 "82421877272e710e24da703bd5c8b9981e8e0a41abc8b8768bac715a75385719"
      def install
        bin.install "mcpt"
      end
    end
  end

  def caveats
    <<~EOS
      To use mcpt as an MCP server in Claude Code, run:
        claude mcp add mcpt #{bin}/mcpt

      To verify it was added:
        claude mcp list
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mcpt --version")
  end
end
